### ISSUE TITLE
Testing with Makergear M2

### ISSUE THREAD

**Issue by ghost** [matt448/OctoPiTouchPanel#1]
Hello Matt, I am the one who noticed your app on Thingiverse, and you directed me to it.  Very Nice app, i like where you are going with it, much cleaner and easier to use on Rpi official 7" display. than the web Touch UI

I am new to Kivy, but was able to install it, and run your app, I thought I would give you some feedback of the things I see/came across: - Note I am testing with a Makergear M2 running Marlin fw

-Installation was fairly simple, however i had to find the Garden.graph module, once it installed the app was up and running on my RPI.
-i found that i had to put the port (in my case :5000) after the IP address in octoprint.cfg - once i did this the app connected to the printer.
-once connected to the printer i tested the control first, Works very well, very responsive, however for some reason my axis's seem to be inverted (all 3) perhaps your configuration and mine differ in which way is positive and negative? - a polite suggestion would be to perhaps add an Invert axis option?
-Temperature control, Again, works well, the only thing I see here is that your bed limit is 100°C... I routinely heat my bed to 110°C to 115°C for printing ABS.

Thank you for Sharing your efforts with this, I am very excited to find this.  

As i said, I am new to Kivy, I have modest programming experience in a few languages C++ VB, and a long time ago Assembly...as well i am somewhat rusty with Linux, that being said, i would be willing to spend some time assisting with testing, or perhaps even code. Either way, thank you!

**Comment by matt448** [comment]
Thanks for all the feedback! You are are the first person I've gotten any feedback from. I'm excited to finally have someone else's input.
- The Garden.graph module is a pain. I'm considering replacing it with some other method of generating the graphs.
- Interesting on the port number. I don't have to do that on my install. Maybe I can add a note in the config file.
- Certainly very easy to add config option for the inverted axis. I'm thinking three separate config options so each axis can be set inverted separately.
- For temperature control I think I will add config options for max temp for both the hot end and the bed.

I welcome whatever help you would like to provide. I'll try and get to some of these items this week. I have several other features that I want to add too. Things like extruding filament, adjusting extrusion rate, setting fan speed, buttons to pause/resume and cancel print jobs.

**Comment by matt448** [comment]
@SCHMENKE I committed changes to the master branch that add configuration options for max temps and axis inversion. When you get a chance pull down the latest code and sample config and give it a try. Let me know how it goes.

**Comment by ghost** [comment]
I have tested your updates to the Axis Inversion. and Max Temps  This works well.  Thank you.

I have both a 3D Printer (actually 2) and a Marlin RAMPs based CNC machine.
I have had a look at the code and for my CNC specific needs i have created a custom version that has a "CNC Mode" configurable in the octoprint.cfg 
The additions are as follows:
- "Zero" buttons for all axes separately, plus one for all axes at once using the /api/printer/command  to send arbitrary Gcode G92 {X,Y,Z}
- Spindle Start/Stop buttons.

I have also added a Feedrate slider (using the M220 command) on the Control tab.
and a Baudrate configuration entry in the octoprint.cfg file, as my firmware is working better at a baudrate of 115200

I am new to Github, Kivy and Python, so i am not sure if/how to share the code... I can post it if you would like to review it.

Your planned enhancements all seem quite useful, The Temperature sliders do seem to work quite well, for me, but a preset ABS and a Preset PLA button would be nice.  As per the question of weather or not to set the temp directly, or move the sliders, My vote is for setting the temp directly as if the preset that is set in the cfg file is not exactly what you want, its easy enough to make the adjustment via the sliders.

**Comment by matt448** [comment]
Sending a pull request is perfect. I'll review it in the next couple days. I'm going to close this issue since the axis inversion and max temp features work for both of us.
