### ISSUE TITLE
Add Extruder control buttons

### ISSUE THREAD

**Issue by ghost** [matt448/OctoPiTouchPanel#12]
I was just switching filament in preparation for starting a print.  I realized that the control screen does not have extruder controls.  Perhaps buttons for extrude and retract?  My suggestion would be to have four buttons  one each for extrude slow, Extrude fast, retract slow and retract fast, they could also be linked to the 4 buttons for selecting the amount of movement.

**Comment by matt448** [comment]
I think this one is the highest priority on my list.

**Comment by matt448** [comment]
@SCHMENKE I added extrude and retract buttons to the Control screen. There is also a new selector for choosing the extrusion distance. Pull down the latest version of master to try it out.
