### ISSUE TITLE
Issues executing OctoPiTouchPanel from Pi

### ISSUE THREAD

**Issue by ghost** [matt448/OctoPiTouchPanel#17]
Greetings Matt, I have been trying to get the touch panel to startup on the Raspberry pi desktop via an Icon, rather than using the terminal or a SSH session.  I cannot figure out how to get it to work.  It seems like it is not properly accessing the octoprint.cfg file.

Any Ideas?

the app also seems to time out after a while and end, I am not sure if this is due to the fact that i am launching from a SSH session...

**Comment by ghost** [comment]
Sorry to bother you with this Matt, I was able to get the Launcher to work with the following .desktop launcher file:

[Desktop Entry]
Name=M2 Controller
Comment=Controls the Makergear M2 3D Printer
Exec=python /home/pi/OctoPiTouchPanel/main.py
Path=/home/pi/OctoPiTouchPanel
Icon=/home/pi/OctoPiTouchPanel/img/Icon_Logo_96x96.png
Type=Application
Encoding=UTF-8
Terminal=false

as well, The app seems to continue to run when not launched from the SSH session. 

you can close this issue.

**Comment by matt448** [comment]
@SCHMENKE Glad you got that figured out. Thanks for the info.
