### ISSUE TITLE
Add fan control to the 'Control' tab

### ISSUE THREAD

**Issue by matt448** [matt448/OctoPiTouchPanel#4]
New feature to control the cooling fan. Needs to use the arbitrary command api.

http://docs.octoprint.org/en/master/api/printer.html#send-an-arbitrary-command-to-the-printer
- Add button for 'Fan Off'
- Add button for 'Set Fan'
- Add slider to set fan speed 0-100%

**Comment by ghost** [comment]
I like it!

The Spindle start/stop buttons that i created in my pull request could be re-named for Fan Start and Fan stop (If Not cnc:) as by default the fan output is what is used for spindle control on a Marlin based CNC.

**Comment by matt448** [comment]
Feature added. https://github.com/matt448/OctoPiTouchPanel/pull/18
