### ISSUE TITLE
Create a new 'Job' tab with job controls

### ISSUE THREAD

**Issue by matt448** [matt448/OctoPiTouchPanel#6]
New Job tab with controls to pause, resume, cancel jobs.

Maybe a reprint button too.

**Comment by ghost** [comment]
I know it may be difficult, but what about an option to start a print from the files that have been uploaded to the Raspberry Pi?

**Comment by matt448** [comment]
@SCHMENKE I like that. Kivy does have a file browser widget so I don't think it will be too bad to add. I'll create another enhancement issue with that feature.

**Comment by matt448** [comment]
Started work on this. Using branch feature-job-controls

**Comment by matt448** [comment]
Done. Merged feature-job-controls into master.

![screenshot 2016-07-16 19 30 16](https://cloud.githubusercontent.com/assets/1915784/16898001/ed828726-4b8b-11e6-819f-5244041aec10.png)

![screenshot 2016-07-16 19 30 30](https://cloud.githubusercontent.com/assets/1915784/16898003/f4e262d4-4b8b-11e6-91eb-860511fe34dd.png)

![screenshot 2016-07-16 19 30 51](https://cloud.githubusercontent.com/assets/1915784/16898004/f973e37c-4b8b-11e6-8853-6b1bb1efd3d6.png)
